print(" -"+"-"*47)
print("|                                                |")
print("|    01HelloWorld                                |")
print("|    Name : Jennica Wang                         |")
print("|    Version : 01                                |")
print("|                                                |")
print(" -"+"-"*47)
print("Hello World")